"""Official Python SDK for the Conduit API."""

from .client import (
    Conduit,
    MatchingJobReceipt,
    MatchingRunHandle,
    ReportJobReceipt,
    ReportRunHandle,
)
from .errors import (
    ApiError,
    AuthError,
    ConduitError,
    InitializationError,
    InsufficientCreditsError,
    InvalidSourceError,
    JobCanceledError,
    JobFailedError,
    RateLimitError,
    RemoteFetchError,
    RemoteFetchTimeoutError,
    RemoteFetchTooLargeError,
    RequestAbortedError,
    SourceError,
    StreamError,
    UnsupportedRuntimeError,
    ValidationError,
    WebhookVerificationError,
)
from .errors import (
    TimeoutError as SDKTimeoutError,
)
from .models import (
    Entity,
    FileDeleteReceipt,
    Job,
    JobEvent,
    ListEntitiesResponse,
    ListFilesResponse,
    MatchingAnalysisResponse,
    MediaFile,
    MediaObject,
    Report,
    RetentionLockResult,
    WebhookEvent,
)

TimeoutError = SDKTimeoutError

__all__ = [
    "ApiError",
    "AuthError",
    "Conduit",
    "ConduitError",
    "Entity",
    "FileDeleteReceipt",
    "InitializationError",
    "InsufficientCreditsError",
    "InvalidSourceError",
    "Job",
    "JobCanceledError",
    "JobEvent",
    "JobFailedError",
    "ListEntitiesResponse",
    "ListFilesResponse",
    "MatchingAnalysisResponse",
    "MatchingJobReceipt",
    "MatchingRunHandle",
    "MediaFile",
    "MediaObject",
    "RateLimitError",
    "RemoteFetchError",
    "RemoteFetchTimeoutError",
    "RemoteFetchTooLargeError",
    "Report",
    "ReportJobReceipt",
    "ReportRunHandle",
    "RequestAbortedError",
    "RetentionLockResult",
    "SourceError",
    "StreamError",
    "TimeoutError",
    "UnsupportedRuntimeError",
    "ValidationError",
    "WebhookEvent",
    "WebhookVerificationError",
]
